import { GoogleGenAI } from "@google/genai";

export interface GeminiClient {
  generateContent(prompt: string): Promise<string>;
  generateImageBase64(prompt: string): Promise<string>;
}

export class DefaultGeminiClient implements GeminiClient {
  private ai: GoogleGenAI;

  constructor(apiKey?: string) {
    this.ai = new GoogleGenAI({ apiKey: apiKey || process.env.GEMINI_API_KEY });
  }

  async generateContent(prompt: string): Promise<string> {
    const response = await this.ai.models.generateContent({
      model: "gemini-2.0-flash", // Assuming 2.0 flash
      contents: prompt,
    });
    
    return response.text || "";
  }

  async generateImageBase64(prompt: string): Promise<string> {
    const response = await this.ai.models.generateImages({
      model: "imagen-4.0-fast-generate-001",
      prompt: prompt,
      config: {
        outputMimeType: "image/jpeg",
      }
    });

    const base64Image = response.generatedImages?.[0]?.image?.imageBytes;
    if (!base64Image) {
      throw new Error("No image generated by Gemini API");
    }

    return base64Image;
  }
}
